#!/bin/sh
# Builds the Swift package and assembles BatteryLimiter.app.
# No Xcode project is used -- SPM + a bundle wrapper is enough for a
# menu bar app, and it's a much shorter path without a paid Developer ID.
set -e
cd "$(dirname "$0")/.."

swift build -c release

APP="BatteryLimiter.app"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS"

cp .build/release/BatteryLimiter "$APP/Contents/MacOS/BatteryLimiter"
cp .build/release/BatteryLimiterHelper "$APP/Contents/MacOS/battery-limiter-helper"
cp Sources/BatteryLimiter/Info.plist "$APP/Contents/Info.plist"

# Build the .icns from icon.png rather than committing one: sips and iconutil
# ship with macOS, and this keeps a single image in the repo instead of a
# multi-megabyte binary that has to be regenerated by hand when the art changes.
ICONSET="$(mktemp -d)/AppIcon.iconset"
mkdir -p "$ICONSET"
for s in 16 32 128 256; do
    sips -Z "$s" icon.png --out "$ICONSET/icon_${s}x${s}.png" >/dev/null
    sips -Z "$((s * 2))" icon.png --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null
done
sips -Z 512 icon.png --out "$ICONSET/icon_512x512.png" >/dev/null
mkdir -p "$APP/Contents/Resources"
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/AppIcon.icns"
rm -rf "$(dirname "$ICONSET")"

# Ad-hoc sign: no Developer ID, but SMAppService.mainApp.register() and
# launchd both require *some* signature to be present. Must run after the
# icon lands, or the bundle's signature won't cover it.
codesign --force --deep --sign - "$APP"

echo "Built $APP"
